import localFont from "next/font/local";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import Navbar from "../Components/(Shared)/Navbar/Navbar";
import Footer from "../Components/(Shared)/Footer/Footer";
import SecondFooter from "../Components/(Shared)/Footer/SecondFooter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Pharmacy Web",
  description: "Generated by Pharmacy Web",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <AntdRegistry>{children}</AntdRegistry>
        <Footer />
        <SecondFooter />
      </body>
    </html>
  );
}
